name: Build
on:
  push:
    branches: # avoid duplicate workflows on tag
      - '**'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          distribution: adopt-openj9
          java-version: 11.0.11+9
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify